proc main
push 6
push 5
pop r0
pop r1
add r0 r1
push r0

push 4
pop r0
pop r1
add r0 r1
push r0

push 3
pop r0
pop r1
add r0 r1
push r0

push 2
pop r0
pop r1
add r0 r1
push r0

push 1
pop r0
pop r1
add r0 r1
push r0

push a
push 5
pop r0
pop r1
add r0 r1
push r0

push 4
pop r0
pop r1
add r0 r1
push r0

push 3
pop r0
pop r1
add r0 r1
push r0

push 2
pop r0
pop r1
add r0 r1
push r0

push 1
pop r0
pop r1
add r0 r1
push r0

