proc print
push aaa
push bbb
proc main
push 50
pop r0
setvar a r0
push 50
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar b r0
push 50
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar c r0
push 50
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar d r0
push 50
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar e r0
push 50
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar f r0
push 50
push f
pop r0
pop r1
add r0 r1
push r0
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar g r0
push 50
push g
pop r0
pop r1
add r0 r1
push r0
push f
pop r0
pop r1
add r0 r1
push r0
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar h r0
push 50
push h
pop r0
pop r1
add r0 r1
push r0
push g
pop r0
pop r1
add r0 r1
push r0
push f
pop r0
pop r1
add r0 r1
push r0
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar i r0
push 50
push i
pop r0
pop r1
add r0 r1
push r0
push h
pop r0
pop r1
add r0 r1
push r0
push g
pop r0
pop r1
add r0 r1
push r0
push f
pop r0
pop r1
add r0 r1
push r0
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar j r0
push 50
push j
pop r0
pop r1
add r0 r1
push r0
push i
pop r0
pop r1
add r0 r1
push r0
push h
pop r0
pop r1
add r0 r1
push r0
push g
pop r0
pop r1
add r0 r1
push r0
push f
pop r0
pop r1
add r0 r1
push r0
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar k r0
push 50
push k
pop r0
pop r1
add r0 r1
push r0
push j
pop r0
pop r1
add r0 r1
push r0
push i
pop r0
pop r1
add r0 r1
push r0
push h
pop r0
pop r1
add r0 r1
push r0
push g
pop r0
pop r1
add r0 r1
push r0
push f
pop r0
pop r1
add r0 r1
push r0
push e
pop r0
pop r1
add r0 r1
push r0
push d
pop r0
pop r1
add r0 r1
push r0
push c
pop r0
pop r1
add r0 r1
push r0
push b
pop r0
pop r1
add r0 r1
push r0
push a
pop r0
pop r1
add r0 r1
push r0
pop r0
setvar l r0
push a
push b
push c
call print
push 102400
pop r0
setvar z r0
